#!/usr/bin/env bash
# set -o errexit

# N4IRS 07/26/2017

#################################################
#                                               #
#                                               #
#                                               #
#################################################

systemctl start nxdngateway.service
systemctl start nxdnparrot.service
systemctl start p25gateway.service
systemctl start p25parrot.service
systemctl start ysf2dmr.service
systemctl start ysf2nxdn.service
systemctl start ysf2p25.service
systemctl start ysfgateway.service
systemctl start ysfparrot.service
systemctl start mmdvmhost.service

