#! /bin/sh

#####################################################
#                                                   #
#    Program firmware for the STM32_DVM_USB         #
#                                                   #
#####################################################

test -e bin/mmdvm.hex || exit 1

stm32flash -w bin/mmdvm.hex -v /dev/ttyUSB0


